### ISSUE TITLE
Metamath doesn't work in interactive mode in a browser

### ISSUE THREAD

**Issue by Antony74** [jcaesar/wapm-pkg#1]
Hi, thanks for creating this project, again.

We both knew this all along, but if you run Metamath in a browser-based WebAssembly.sh without piping commands to it, you get that ugly Window.prompt asking you for a command.  And worse still stdout doesn't flush before the next Window.prompt, so you have no idea what the response to your first command was before you have to enter the second one.

What's interesting is why this doesn't work, and the fact that @wasmer/wasm-terminal is [programmed](https://github.com/wasmerio/wasmer-js/blob/55fa8c17c56348c312a8bd23c69054b1aa633891/packages/wasm-terminal/src/command-runner/command-runner.ts#L162) to support familiar command entry behaviour, but falls back on Window.prompt if SharedArrayBuffer is not available.

Obviously JavasScript is mostly a single-threaded async platform, and that's mostly the way I like it!  This does however mean that the only way to get correct blocking while awaiting command entry behaviour (without freezing everything else a browser might be doing) is to run the shell program inside a WebWorker.  That's where the SharedArrayBuffer comes in, to facility communication between the worker and the main thread.  For security reasons SharedArrayBuffer is now only available if [cross-origin isolation headers](https://blog.logrocket.com/understanding-sharedarraybuffer-and-cross-origin-isolation/) are set.

I've tried setting them locally with [this simple script](https://github.com/Antony74/webassembly.sh/blob/feature/metamath/express.js), and am happily able to use Metamath in browser interactively.  Also it can still access the wapm repository fine - whatever it is those headers isolate us from, it doesn't appear to affect the normal running of WebAssembly.sh.

Do you happen to know why these headers have not been set on any online resources that provide a WebAssembly.sh?  Or do you have any other thoughts or observations about this issue, please?

I'm going to try and upload a fully working and interactive WebAssembly.sh into my aws account, to further demonstrate the avoidability of Window.prompt, but that's going to take some time because:

1. The build of WebAssembly contains absolute paths and expects to be in the root folder of a domain.
2. My websites are all s3 buckets with the static hosting switched on, so adding the cross-origin isolation headers is going to take a fair bit of screwing around with a slightly different infrastructure.

**Comment by Antony74** [comment]
> I'm going to try and upload a fully working and interactive WebAssembly.sh into my aws account, to further demonstrate the avoidability of Window.prompt

Done

https://d1mtql0za68dbm.cloudfront.net/

Now you don't have to take my word for it ;-)

**Comment by jcaesar** [comment]
Oh wow. I was aware that this should be possible somehow (even without shared byte arrays?), but I didn't think it was this easy. I suspect the current situation is a remnant of the Spectre bug panic, but I don't know. The webassembly.sh repo hasn't been touched in 2 years, and imho gives off more of a "tech stunt" feel than a serious project.

Anyway, there's nothing I can do about this from the metamath binary side, right? Maybe ask @syrusakbary (on slack?) whether he'd accept a PR on webassembly.sh in this direction?

**Comment by Antony74** [comment]
> Anyway, there's nothing I can do about this from the metamath binary side, right? 

Right.  But I knew I could count on you to suggest a useful way forward.  Thank you very much for your reply.

webassembly.sh is a front-end program, and as far as I'm aware cross-origin isolation can only be set on the back-end.  So I'm afraid a PR won't help, it's a matter of server configuration.  (Hence why I was messing around with CloudFront, which, believe me, was not for fun!).  So first we would need to identify the main servers that are affected.  These are the websites I'm aware of

https://wapm.io
https://webassembly.sh

And of course it's up to the owners of these sites to determine the desirability (and any potential downsides) of a proposed change in configuration.

Then would need to find the right place to start a conversation about it.  I'm inclined to agree with you that Github Issues is not the right place, because when I opened [an issue pointing out the wasmer-js repo is broken](https://github.com/wasmerio/wasmer-js/issues/280), folks seem to think it's been abandoned.

I'll have to create a Slack account, because currently I only use Slack internally for work.  Which Slack channel so you think I should post on? - starting a conversation and 'at'-ing who I think can help with the question is generally a much more flexible way of solving a problem.

> gives off more of a "tech stunt" feel than a serious project.

Even as a stunt, it's far more impressive if you can interact with the programs' own command prompts!

**Comment by Antony74** [comment]
> Oh wow. I was aware that this should be possible somehow (even without shared byte arrays?)

How would you go about doing it without SharedByteArray, please - just so I know?  Some sort of alternative mechanism for communication between web-worker and main thread perhaps.

Just as an aside, I thought you might like to know that once I removed the last obstacle to using metamath in WebAssembly.sh, I let the metamath mailing list know:

https://groups.google.com/g/metamath/c/YmnL0J3avSk/m/2tkKmfjBAQAJ

Thanks again for this wasm build of metamath!

(as I note in that message, not all browsers support he SharedByteArray with cross-origin isolation - of the browsers I've tried, Chrome, Firefox, and Edge work fine, Safari does not)

**Comment by jcaesar** [comment]
Apparently, https://tokera.sh is supposed to understand `wapm install` and interactive mode. For some reason, it doesn't work for me, but I figured you might want to test it?

**Comment by Antony74** [comment]
That's very interesting, thank you very much.  Given there are two WebAssembly shells out there that fail to run Metamath interactively in interesting and different ways, I think I might stick to hosting my own!
