### ISSUE TITLE
failed to verify set.mm locally on mac

### ISSUE THREAD

**Issue by mountain** [jcaesar/wapm-pkg#2]
Hi, jcaesar,

Thanks for your contribution first.

Following you guide on https://wapm.io/package/liftm/metamath, I had verified set.mm successfully in browser.

But after I install wapm by brew on Mac, I tried the same commands

```bash
curl https://raw.githubusercontent.com/metamath/set.mm/d3dc8f9545186d55b90dd8f4d89ff8e2ec2a3b93/set.mm -o set.mm
metamath "read set.mm" "verify proof *" exit
```

It failed by below information:

```text
Metamath - Version 0.198 7-Aug-2021           Type HELP for help, EXIT to exit.
MM> read set.mm
         ^^^^^^
?Sorry, couldn't open the file "set.mm".
MM> verify proof *
?No source file has been read in.  Use READ first.
MM> exit
```

Could you help with this?

Mingli

**Comment by jcaesar** [comment]
Try running metamath as
```
metamath --dir .
```
or
```
wapm run metamath --dir .
```
and then inputting the metamath commands at the prompt.

**Comment by jcaesar** [comment]
Maybe I need to add a 
```toml
[fs]
"."="."
```
to the spec… Hm.

**Comment by mountain** [comment]
Thanks for your comment, jcaesar.
